---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: sso
  name: oauth2-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sso
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      serviceAccountName: oauth2-proxy
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
        args:
        - --cookie-domain=istio-okta.local
        - --cookie-expire=3h
        - --cookie-name=sessionid
        - --cookie-refresh=1h
        - --cookie-samesite=lax
        - --cookie-secure=false
        - --email-domain=*
        - --force-https=false
        - --http-address=0.0.0.0:8080
        - --pass-access-token=true
        - --pass-user-headers=true
        - --provider=oidc
        - --redis-connection-url=redis://redis.sso.svc.cluster.local:6379
        - --session-store-type=redis
        - --set-authorization-header=true
        - --set-xauthrequest=true
        - --silence-ping-logging=true
        - --skip-provider-button=true
        - --upstream=static://200
        - --whitelist-domain=.okta.com
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            configMapKeyRef:
                name: oauth2-proxy
                key: client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
                name: oauth2-proxy
                key: client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
                name: oauth2-proxy
                key: cookie_secret
        - name: OAUTH2_PROXY_LOGIN_URL
          valueFrom:
            configMapKeyRef:
                name: oauth2-proxy
                key: login_url
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          valueFrom:
            configMapKeyRef:
                name: oauth2-proxy
                key: oidc_issuer_url
        - name: OAUTH2_PROXY_OIDC_JWKS_URL
          valueFrom:
            configMapKeyRef:
                name: oauth2-proxy
                key: oidc_jwks_url
        - name: OAUTH2_PROXY_REDEEM_URL
          valueFrom:
            configMapKeyRef:
                name: oauth2-proxy
                key: redeem_url
        - name: OAUTH2_PROXY_SCOPE
          value: "openid email profile offline_access"
        - name: OAUTH2_PROXY_VALIDATE_URL
          valueFrom:
            configMapKeyRef:
                name: oauth2-proxy
                key: validate_url
---
apiVersion: v1
kind: Service
metadata:
  namespace: sso
  name: oauth2-proxy
  labels:
    name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: oauth2-proxy
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oauth2-proxy
  namespace: sso
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: oauth2-proxy
  rules:
  - from:
    - source:
        namespaces: ["istio-system"]
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
