---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sso
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.12
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: sso
  name: redis
  labels:
    name: redis
spec:
  ports:
  - name: tcp
    port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: redis
  namespace: sso
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: redis
  rules:
  - from:
    - source:
        namespaces: ["sso"]
        principals: ["cluster.local/ns/sso/sa/oauth2-proxy"]
