---
# mesh wide config: enfore mTLS for all communications
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  namespace: istio-system
  name: default
spec:
  mtls:
    mode: STRICT
---
# mesh wide config: deny all traffic in the first place
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   namespace: istio-system
#   name: deny-all
# spec:
#   {}
