# IstioOperator Options: https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      holdApplicationUntilProxyStarts: true
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        replicaCount: 2
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        replicaCount: 2
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        replicaCount: 2
