[package]
name = "hw"
version = "0.1.0"
authors = ["thiagocaiubi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hw"
path = "hw.rs"
